AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'shaw3-sam3-test'
      
  UploadFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'upload_function.handler'
      Runtime: 'python3.11'
      CodeUri: './'
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3Bucket
      Events:
        UploadApi:
          Type: 'Api'
          Properties:
            Path: '/upload'
            Method: 'post'

  DownloadFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'download_function.handler'
      Runtime: 'python3.11'
      CodeUri: './'
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref S3Bucket
      Events:
        DownloadApi:
          Type: 'Api'
          Properties:
            Path: '/download'
            Method: 'get'
